services:
  app:
    container_name: mcsm-daemon
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_IMAGE:-ngc7331/mcsmanager-daemon}:${DOCKER_TAG:-latest${MCSM_JDK_VERSION:-}}
    restart: unless-stopped
    networks:
      - default
    volumes:
      - data:/opt/mcsm/daemon/data:rw
    environment:
      - TZ
      - PUID
      - PGID
      - JAVA_VERSION
      - PLUGIN

volumes:
  data:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
