services:
  app:
    container_name: qbittorrent
    image: ${DOCKER_MIRROR:-lscr.io}/${DOCKER_IMAGE:-linuxserver/qbittorrent}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    networks:
      - default
    ports:
      - ${PORT_BITTORRENT:-6881}:${PORT_BITTORRENT:-6881}/tcp # BitTorrent TCP connection port
      - ${PORT_BITTORRENT:-6881}:${PORT_BITTORRENT:-6881}/udp # BitTorrent UDP connection port
    volumes:
      - config:/config:rw
      - ${VOLUME_PATH_DOWNLOADS:-downloads}:/downloads:rw
    environment:
      - TZ
      - PUID
      - PGID

volumes:
  config:
  downloads:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
