services:
  app:
    container_name: ddns-go
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_IMAGE:-jeessy/ddns-go}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    network_mode: host
    volumes:
      - data:/root:rw
    environment:
      - TZ
      - PUID
      - PGID

volumes:
  data:
