services:
  app:
    container_name: calibre-web
    image: ${DOCKER_MIRROR:-lscr.io}/${DOCKER_IMAGE:-linuxserver/calibre-web}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    networks:
      - default
    ports: []
    volumes:
      - config:/config:rw
      - ${VOLUME_PATH_DATA:-data}:/books:rw
    environment:
      - TZ
      - PUID
      - PGID
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE

volumes:
  config:
  data:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
