services:
  app:
    container_name: frpc
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_IMAGE:-ngc7331/frpc}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    networks:
      - default
    volumes:
      - config:/config:rw
    environment:
      - TZ
      - PUID
      - PGID
      - SERVER_ADDR
      - SERVER_PORT
      - AUTH_TOKEN
      - WEBUI_PASS
      - PROXY_USER

volumes:
  config:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
