services:
  app:
    container_name: komga
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_IMAGE:-gotson/komga}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    networks:
      - default
    ports: []
    volumes:
      - config:/config:rw
      - ${VOLUME_PATH_DATA:-data}:/data:rw
    environment:
      - TZ
      - PUID
      - PGID

volumes:
  config:
  data:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
