services:
  app:
    container_name: gitea
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_IMAGE:-gitea/gitea}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    networks:
      - default
    ports: []
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ
      - PUID
      - PGID
      - USER_UID=${PUID}
      - USER_GID=${PGID}

volumes:
  data:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
