services:
  app:
    container_name: syncthing
    image: ${DOCKER_MIRROR:-lscr.io}/${DOCKER_IMAGE:-linuxserver/syncthing}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    networks:
      - default
    ports:
      - 22000:22000/tcp  # sync tcp
      - 22000:22000/udp  # sync udp
      - 21027:21027/udp  # discovery
    volumes:
      - config:/config:rw
      - ${VOLUME_PATH_DATA:-data}:/data:rw
    environment:
      - TZ
      - PUID
      - PGID

volumes:
  config:
  data:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
