services:
  app:
    container_name: jellyfin
    image: ${DOCKER_MIRROR:-lscr.io}/${DOCKER_IMAGE:-linuxserver/jellyfin}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    networks:
      - default
    ports:
      - 1900:1900/udp # Service discovery used by DNLA and clients
      - 7359:7359/udp # Jellyfin service discovery
    volumes:
      - config:/config:rw
      - ${VOLUME_PATH_DATA:-data}:/data:rw
    environment:
      - TZ
      - PUID
      - PGID
      - JELLYFIN_PublishedServerUrl
      - DOCKER_MODS

volumes:
  config:
  data:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
