services:
  app:
    container_name: frps
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_IMAGE:-ngc7331/frps}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    networks:
      - default
    ports:
      - ${PORT_SERVER:-7000}:7000/tcp  # server port
      - ${PORT_PROXY_LO:-57000}-${PORT_PROXY_HI:-57100}:${PORT_PROXY_LO:-57000}-${PORT_PROXY_HI:-57100}/tcp  # proxy ports
      - ${PORT_PROXY_LO:-57000}-${PORT_PROXY_HI:-57100}:${PORT_PROXY_LO:-57000}-${PORT_PROXY_HI:-57100}/udp  # proxy ports
    volumes:
      - config:/config:rw
    environment:
      - TZ
      - PUID
      - PGID
      - AUTH_TOKEN
      - WEBUI_USER
      - WEBUI_PASS

volumes:
  config:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
