services:
  app:
    container_name: v2raya
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_IMAGE:-mzz2017/v2raya}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    networks:
      - default
    ports:
      - 2017:2017/tcp
      - 20170-20172:20170-20172/tcp
      - 20170-20172:20170-20172/udp
    volumes:
      - config:/etc/v2raya
    environment:
      - TZ
      - PUID
      - PGID
      - V2RAYA_LOG_FILE=/tmp/v2raya.log
      - V2RAYA_V2RAY_BIN=/usr/local/bin/xray

volumes:
  config:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
