services:
  astrbot:
    container_name: bot-astrbot
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_IMAGE:-soulter/astrbot}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    networks:
      - default
    volumes:
      - astrbot-data:/AstrBot/data:rw
    environment:
      - TZ=Asia/Shanghai
      - WEREAD_API_KEY

volumes:
  astrbot-data:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
