services:
  app:
    container_name: npm
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_IMAGE:-jc21/nginx-proxy-manager}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    networks:
      - default
    ports:
      - 80:80/tcp
      - 81:81/tcp
      - 443:443/tcp
    volumes:
      - data:/data:rw
      - cert:/etc/letsencrypt:rw
    environment:
      - TZ
      - PUID
      - PGID

volumes:
  data:
  cert:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
