services:
  app:
    container_name: mcsm-web
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_IMAGE:-ngc7331/mcsmanager-web}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    networks:
      - default
    volumes:
      - data:/opt/mcsm/web/data:rw
    environment:
      - TZ
      - PUID
      - PGID

volumes:
  data:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
