services:
  app:
    container_name: hath
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_IMAGE:-ngc7331/hath}:${DOCKER_TAG:-latest}
    restart: unless-stopped
    networks:
      - default
    ports:
      - ${PORT_HATH:-9996}:${PORT_HATH:-9996}/tcp
    volumes:
      - data:/data:rw
    environment:
      - TZ
      - PUID
      - PGID
      - HATH_CLIENT_ID
      - HATH_CLIENT_KEY

volumes:
  data:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK:-br}
